### 1-1. 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "username" : "username1",
  "password" : "password1!"
}


### 1-2. 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "username" : "username2",
  "password" : "password2!",
  "managerKey" : "AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC"
}