### 2-1. 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "username1",
  "password": "password!!"
}

> {%
    client.global.set("access_token", response.body.data.accessToken);
%}

