### 3-1. USER : 보드 생성
POST http://localhost:8080/api/boards
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "테스트",
  "intro" : "내용 테스트"
}

### 3-2. 보드 수정

PUT http://localhost:8080/api/boards/3
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "테스트2",
  "intro" : "내용 테스트2"
}

### 3-3. 보드 삭제

DELETE http://localhost:8080/api/boards/3
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 3-4. 보드 조회

GET http://localhost:8080/api/boards?page=1
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 3-5. 보드 초대

POST http://localhost:8080/api/boards/2/invite
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "invitedUserId": 2
}